### ISSUE TITLE
安装和使用过程中的遇到的一些问题

### ISSUE THREAD

**Issue by blinking-yan** [wufeifei/cobra#115]
按照wiki里的步骤在centos 7下装了一遍，遇到一些问题：

- mysql服务没有启动

运行 `yum install -y mysql-devel` 后mysql服务没有启动

这里是按照 h[ow-to-install-mysql-on-centos-7](https://www.linode.com/docs/databases/mysql/how-to-install-mysql-on-centos-7) ，装完后启动mysql服务

- 需要自己手动创建数据库 cobra

一开始运行 `python cobra.py install` 后没有输出，访问后页面报错，看了下install部分的源码，发现应该是报错了，但是logging没有打出，加了个print，发现是数据库没有创建.....

- 安装完后，通过填写gitlab地址扫描，提示clone failed

![image](https://cloud.githubusercontent.com/assets/17590163/18621444/29cb90f4-7e56-11e6-97d5-05941e6c9201.png)

私有仓库需要认证的问题，看到之前有人提过issue，希望可以加上哈～

- 通过上传代码扫描，到Tasks tab里找不到查看报表的入口

![image](https://cloud.githubusercontent.com/assets/17590163/18621470/8a7dc1c4-7e56-11e6-88a0-9a2a2806297f.png)

![image](https://cloud.githubusercontent.com/assets/17590163/18621468/85d319c6-7e56-11e6-96a3-dd624680c611.png)

希望能得到解答，多谢～

**Comment by wufeifei** [comment]
1. clone failed
检查config文件中的[upload] -> directory 目录是否创建了，并检查是否有写入权限。

2. 报表在Projects栏目里面

另外，更新下最新的代码

**Comment by blinking-yan** [comment]
@wufeifei 

下载了dvwa的代码，然后上传压缩包，没有扫到一个漏洞，是哪里出了问题吗？


![image](https://cloud.githubusercontent.com/assets/17590163/18623532/00f19a78-7e71-11e6-8017-9dd7c305f7aa.png)

**Comment by wufeifei** [comment]
https://github.com/wufeifei/cobra/wiki/Rules 通过后台添加规则

**Comment by blinking-yan** [comment]
get

**Comment by v1cker** [comment]
@blinking-yan 您好，我在安装的时候也出现类似问题，install 时没有任何输出，database 创建和不创建都没有数据，想问一下您在那个位置打印错误信息呢？ 感谢
