### ISSUE TITLE
建议wiki中安装依赖前增加执行如下命令

### ISSUE THREAD

**Issue by michealzh** [wufeifei/cobra#120]
easy_install -U setuptools

否则报错提示:
Complete output from command python setup.py egg_info:
    The required version of setuptools (>=0.7.7) is not available,
    and can't be installed while this script is running. Please
    install a more recent version first, using
    'easy_install -U setuptools'.
    
    (Currently using setuptools 0.6c11 (/usr/lib/python2.6/site-packages))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 2 in /tmp/pip-build-_TEk9W/ConcurrentLogHandler

**Comment by wufeifei** [comment]
这个不能算作cobra依赖的
