### ISSUE TITLE
依赖太多了，很容易就出错

### ISSUE THREAD

**Issue by grt1st** [wufeifei/cobra#121]
这个项目真的很不错，就是依赖略多：）

**Comment by grt1st** [comment]
无法生成数据库

**Comment by wufeifei** [comment]
不要把提Issue当成咨询客服，这里不是在卖东西。
也不要一句话就把问题描述完了，请带上你的运行环境、你所尝试的方法、你的思考。
这样大家才能解决你的问题。

**Comment by grt1st** [comment]
谢谢耐心的回答我，如果可以我都想关闭这个issue。
一点一点把依赖都装好了，但是建立数据库这里出了问题。
网站无法访问，我一查询数据库发现并没有对应的表。但是在配置文件里的用户名、密码是对的。
所以我应该怎么解决，重新安装？

**Comment by V5h1n3** [comment]
你用的是什么版本的数据库？mysql好像要5.6以上才行

**Comment by hack2012** [comment]
经测试mysql 5.5一样可以安装，只是程序写的有点小问题，没有创建数据库。
需要手工创建数据库以后再执行，改天我会写一个关于这个安装中遇到的问题。
有需要的朋友，可以过段时间访问http://www.waitalone.cn/cobra-install.html

**Comment by grt1st** [comment]
请问怎么手工创建？我mysql确实是5.5

**Comment by hack2012** [comment]
请参考http://www.waitalone.cn/cobra-install.html

**Comment by grt1st** [comment]
现在的问题是一些python依赖明明已经安装，import却会报错。执行python cobra.py install后进入数据库查看为空表。

部分依赖的问题：

```
pi@raspberrypi:~/cobra $ sudo pip install Werkzeug
Requirement already satisfied (use --upgrade to upgrade): Werkzeug in /usr/local/lib/python2.7/dist-packages
Cleaning up...
pi@raspberrypi:~/cobra $ sudo pip install Werkzeug --upgrade
Requirement already up-to-date: Werkzeug in /usr/local/lib/python2.7/dist-packages
Cleaning up...
pi@raspberrypi:~/cobra $ python
Python 2.7.9 (default, Mar  8 2015, 00:52:26) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Werkzeug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Werkzeug

```

**Comment by grt1st** [comment]
使用`pip list`查看发现所有python依赖都已安装，执行`python cobra.py install`时没有任何输出。（乌班图下安装，系统依赖安装的很心累。。

**Comment by grt1st** [comment]
我安装好了。。close吧。。
原来config要这个格式。。。。
```
[database]
mysql: mysql+mysqldb://root:passwd@127.0.0.1:3306/cobra
```
