### ISSUE TITLE
数据库创建问题无显示

### ISSUE THREAD

**Issue by v1cker** [wufeifei/cobra#150]
腾讯云 centos6.4 
python2.7.12    编译安装
pip 8.1.2  get-pip.py 安装
requirment.txt 依赖全部安装完毕

安装流程也走了一遍
但是安装没有任何输出，数据库不能创建，调试  db.create_all() 没有执行
安装流程中mysql-python是yum安装，
是不是因为编译安装所以没有装上mysql-python依赖呢，求请教这种怎么解决，谢谢！

**Comment by blinking-yan** [comment]
之前安装的时候，数据库初始化那一步

```
初始化数据库表结构和数据

python cobra.py install
```

运行后没有输出，但是其实报错了，logging没有打出来

需要手动先创建数据库 cobra，才可以

**Comment by v1cker** [comment]
@blinking-yan 是的啊，可是我创建完数据库之后也是没有任何输出，db.create_all() 方法没有执行，我怀疑是python_mysql 支持没有装好，所以想验证一下问题是不是出在这，我想把logging 打印出来，可是没有找到打印位置， = =，

**Comment by blinking-yan** [comment]
自己安装下mysql-server，然后手动创建数据库cobra，再运行初始化

```
python cobra.py install
```

如果是centos，安装mysql-server,可以参考
```
https://www.linode.com/docs/databases/mysql/how-to-install-mysql-on-centos-7
https://www.linode.com/docs/databases/mysql/how-to-install-mysql-on-centos-6
```

**Comment by v1cker** [comment]
@blinking-yan 您好~~ mysql安装完没有问题的，就是这么安装的，pip环境也全部安装完毕，现在就是 在 install 的时候没有输出，

![qq 20160926162436](https://cloud.githubusercontent.com/assets/10337420/18827548/f24eb9e8-8405-11e6-88a5-0760a9e614b3.png)

![image](https://cloud.githubusercontent.com/assets/10337420/18827438/5ec7d3a8-8405-11e6-82eb-25235a8bb0af.png)

**Comment by blinking-yan** [comment]
flag1没有打出来，说明进到 `except` 里了，logging打不出来的，具体原因我没细看，

你加一个print，就知道为啥错了

```
print("MySQL database error: {0}\nFAQ: {1}".format(e, 'https://github.com/wufeifei/cobra/wiki/Error#mysql'))
```

**Comment by v1cker** [comment]
@blinking-yan 嗯嗯，多谢！！！  找到问题了， 我的mysql版本5.1.7不支持utf8m64 ，多谢，我试试重新调一下问题！！！  十分感谢。

**Comment by blinking-yan** [comment]
你的系统应该是centos 6.x,

升级mysql可以参考 [how-to-upgrade-mysql-5-1-to-mysql-5-5-on-centos-6-7](https://www.zerostopbits.com/how-to-upgrade-mysql-5-1-to-mysql-5-5-on-centos-6-7/)

**Comment by v1cker** [comment]
灰常感谢~~~  已经成功~~~   thinks~~~~
