### ISSUE TITLE
默认安装是不是没有规则呀？

### ISSUE THREAD

**Issue by hack2012** [wufeifei/cobra#152]
N多次出错以后，终于安装好了，但是扫描不出任何东西。DVWA
难道默认规则没有添加？

**Comment by magerx** [comment]
我们的规则，暂时没有开放出来的，李总可以参考wiki中的例子自己先写几条试试看 : )

**Comment by hack2012** [comment]
原来如此，知道了，多谢，我测试一下。
不过你们的这个扫描器，安装很麻烦，也就是我这样的强迫症患者有心思安装完，建议写的更详细一点。
比如说系统版本，python版本等。  python2.7.12 安装不了MySQLdb，改天有空写一些安装中遇到的问题。
