### ISSUE TITLE
能否有一些规则？

### ISSUE THREAD

**Issue by smarttang** [wufeifei/cobra#156]
你好～目前只有一个框架，上手有一定难度，能否提供一些规则用于测试？比如常规的sql注入、xss之类的检测规则？

**Comment by DogeWatch** [comment]
这里有俩规则 https://github.com/wufeifei/cobra/wiki/Rules
不过只是单纯的字符串匹配，没有验证规则，这样的话这个自动审计的误报会很高，所以希望作者能提供个带有验证规则的模板来参考下。

**Comment by wufeifei** [comment]
@smarttang @DogeWatch 
你所看到的那两个规则中是有验证（修复）规则的。
这里需要强调一点，白盒和黑盒在审计上是有区别的，黑盒发现的漏洞一定能够利用，而白盒发现的却不然，更偏向的是解决风险。比如Cobra发现一个request函数存在SSRF，Cobra目前只会判断这个request函数存在漏洞，但不会去判断request被哪些地方调用了。
