### ISSUE TITLE
白名单相关bug与改进建议

### ISSUE THREAD

**Issue by alioth310** [wufeifei/cobra#158]
# 1. [bug] 白名单判断有误
现象：加白后，再次扫描时仍然会显示为“未修复”状态。

原因：判断白名单时，当前文件名和白名单列表分别使用了相对路径和绝对路径。

涉及代码段：engine/core 67-72行
self.file_path：当前文件__绝对__路径，如：/tmp/cobra/uploads/ssrf/ssrf1.php
self.white_list：白名单列表（__相对__路径），如：[u'/ssrf1.php']

修正方法：self.file_path变更为相对路径。

# 2. [bug] 白名单更新后project_id、rule_id为0
现象：白名单编辑功能（/admin/edit_whitelist），编辑后存入数据库的project_id、rule_id变为0。

原因：templates中使用的id为project、rule，json提交时（admin.js）仍然使用的是project、rule，但在controller中读取的是project_id、rule_id，存在不一致，导致实际POST的规则ID和项目ID未被真正传入数据库。

涉及代码段：
app/controller/backend/WhiteListsController.py：99、108-109行。

```python
vc = ValidateClass(request, "whitelist_id", "project", "rule", "path", "reason", "status")
...
whitelist.project_id = vc.vars.project_id
whitelist.rule_id = vc.vars.rule_id
```

app/templates/backend/whitelist/edit_whitelist.html：13-14、23-24行。

```html
<label for="project">Project</label>
<select id="project" class="form-control">
...
<label for="rule">Rule</label>
<select id="rule" class="form-control">
```

app/templates/asset/js/admin.js：454-455、462-463行。

```javascript
var project = $("#project").val();
var rule = $("#rule").val();
...
'project': project,
'rule': rule,
```

修正方法（任一）：
1) 统一为project、rule
app/controller/backend/WhiteListsController.py：108-109行修改为：

```python
whitelist.project_id = vc.vars.project
whitelist.rule_id = vc.vars.rule
```

2) 统一为poject_id、rule_id
app/controller/backend/WhiteListsController.py：99行修改为：

```python
vc = ValidateClass(request, "whitelist_id", "project_id", "rule_id", "path", "reason", "status")
```

app/templates/asset/js/admin.js：454-455、462-463行修改为：

```javascript
var project_id = $("#project").val();
var rule_id = $("#rule").val();
...
'project_id': project_id,
'rule_id': rule_id,
```

# 3. [enhancement] 白名单添加没有判重机制
现象：可以创建相同的白名单；或在report的漏洞列表中，重复执行加入白名单操作。

建议：进行白名单判重，已存在的白名单不再允许重复添加。

# 4. [enhancement]白名单添加、删除操作无确认步骤
现象：report的漏洞列表页，加入白名单时无弹框确认步骤；白名单列表页，删除白名单时无弹框确认步骤。

建议：增加弹框确认，避免误操作。

# 5. [bug] 白名单更新时未更新updated_at
现象：白名单更新时，数据库字段updated_at未更新。

涉及代码段：
app/controller/backend/WhiteListsController.py ：108-112行
添加行
```python
import datetime
whitelist.updated_at = datetime.datetime.now()
```

（如上问题均基于当前最新版 b0c962d ）

**Comment by wufeifei** [comment]
@alioth310 感谢详细的反馈，如果可以请提交[Pull Request](https://github.com/wufeifei/cobra/pulls)直接贡献代码。

**Comment by wufeifei** [comment]
@alioth310 fixed #163
