### ISSUE TITLE
java参数可控性判断规则问题

### ISSUE THREAD

**Issue by V5h1n3** [wufeifei/cobra#162]
请问engine/parse.py文件272行开始的代码中getParameter方法的调用为什么判断为不可控呢？如果是request.getParameter()，获取到的字符串不是来自http请求提交的吗？
代码如下：
`
                    # 是否取外部参数

                    regex_get_param = r'String\s{0}\s=\s\w+\.getParameter(.*)'.format(param_name)

                    get_param = re.findall(regex_get_param, param_block_code)

                    if len(get_param) >= 1 and get_param[0] != '':

                        logging.debug("是否赋值外部取参: 是")

                        logging.info("返回: 不可控 (外部取参)")

                        return False

                    logging.debug("是否赋值外部取参: 否")
`

**Comment by wufeifei** [comment]
截至目前，Java这块的验证修复规则还在完善中，目前Java主要规则主要是定位规则。
