### ISSUE TITLE
扫描时出现Key verify failed

### ISSUE THREAD

**Issue by RastlinLiu** [wufeifei/cobra#177]
feifei您好，我在搭建您的系统的时候，设定了扫描地址后，出现Key verify failed报错。粗略的看了一下代码，感觉是应该需要一些初始化数据？不知道是否理解正确。看到您文档中提到需要先走完安装流程，然而https://github.com/wufeifei/cobra/wiki/Installation 都会重定向到您的项目首页，http://cobra-docs.readthedocs.io/en/latest/installation/ 这个地址的内容我都按照步骤做完了，不知道有什么步骤漏掉了。百忙之中希望您能抽空答疑解惑，谢谢。

**Comment by wufeifei** [comment]
1. 文档链接已更新
2. Key verify failed问题更新至[FAQ](http://cobra-docs.readthedocs.io/en/latest/FAQ/)里

感谢反馈

**Comment by RastlinLiu** [comment]
Hi 您好，感谢您给予反馈，看到您FAQ提及说这种情况是因为secret_key未配置，我想请问一下，这个字段应该配置为什么key的md5值？不是很明白这个配置的具体含义，百忙中打扰，如能解答，万分感谢。

**Comment by wufeifei** [comment]
secret_key用来加密session和cookie的，你可以设定成任何一个随机数。比如os.urandom(24) or hashlib.sha1('your_password').hexdigest()

**Comment by RastlinLiu** [comment]
hi 感谢您的反馈，抱歉再次打扰您，我发现docs下面的table.md建表语句有一些滞后？今天我看到程序报错如下：
(_mysql_exceptions.OperationalError) (1054, "Unknown column 'vuls.third_v_id' in 'field list'") [SQL: u'SELECT vuls.id AS vuls_id, vuls.name AS vuls_name, vuls.description AS vuls_description, vuls.repair AS vuls_repair, vuls.third_v_id AS vuls_third_v_id, vuls.created_at AS vuls_created_at, vuls.updated_at AS vuls_updated_at \nFROM vuls']
而table.md内关于Vuls表的建表语句如下
Vuls - 漏洞类型表
```
CREATE TABLE `vuls` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(56) NOT NULL,
  `description` varchar(512) NOT NULL,
  `repair` varchar(512) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
可以看到很多字段都是没有的，我之前使用table.md中表结构自己初始化了数据库，似乎无法让程序正常运行，如能解答，万分感谢
