### ISSUE TITLE
语义分析时没有考虑注释

### ISSUE THREAD

**Issue by tuola** [wufeifei/cobra#251]
代码：
`<?php

function callback(){  

    $callback_url = $_GET['url'];

    $ch = curl_init(); 

    curl_setopt($ch, CURLOPT_URL, $callback_url);

    curl_setopt($ch, CURLOPT_HEADER, 0);

    //curl_setopt($ch, CURLOPT_PROTOCOLS, CURLPROTO_HTTP | CURLPROTO_HTTPS); 

    curl_exec($ch);

    curl_close($ch);

}

?>
`
规则：
`
regex_location：curl_setopt\s?\(.*,\s?CURLOPT_URL\s?,(.*)\)

regex_repair：   curl_setopt\s?\(.*,\s?CURLOPT_PROTOCOLS\s?,(.*)\)
block_repair：    1
`
期望结果：ssrf
实际结果：none(没有考虑到注释的语句不会执行)
建议：分析注释

**Comment by wufeifei** [comment]
注释等情况会在扫描时过滤的，规则不需要考虑过滤问题。
