### ISSUE TITLE
No "Wow, no vulnerability was detected :)" on all project analysis

### ISSUE THREAD

**Issue by FreelancePentester** [wufeifei/cobra#270]
Hi,
I tried to use cobra to analysis for all project (dvwa, bwapp...), the result is alway "Wow, no vulnerability was detected :)".
Thanks!

**Comment by wufeifei** [comment]
By default Cobra does not integrate any scanning rules, so no vulnerabilities are detected.

You can refer to our default provides some [scanning rules](http://cobra-docs.readthedocs.io/en/latest/rule_list/) of the example, follow-up we have plans to open all of our private scanning rules.

**Comment by FreelancePentester** [comment]
thanks!
