### ISSUE TITLE
规则是只支持正则表达式么。

### ISSUE THREAD

**Issue by stayliv3** [wufeifei/cobra#281]
想了解一下关于规则编写的相关内容。

**Comment by wufeifei** [comment]
定位和搜索规则是使用正则来匹配的，对于参数是否可控以及风险判断是扫描引擎的语法解析模块判断的。

对于具体的规则编写，这里有一篇介绍：
http://wufeifei.com/scan-engine/

**Comment by stayliv3** [comment]
感谢。基本懂了。自己需要写定位规则和修复规则，其实就是1个或者2个正则表达式。是这样吧。demo里如果可以提供2-3个可以使用的规则对于使用和了解cobra这个项目应该会有更多的帮助。感谢开源~

**Comment by wufeifei** [comment]
这里有几个不同类型的参考规则
http://cobra-docs.readthedocs.io/en/latest/rule_list/
