### ISSUE TITLE
规则问题

### ISSUE THREAD

**Issue by eleveni386** [wufeifei/cobra#282]
这个项目的关注度好低吖, 平台框架是好的, 但是缺少最核心的东西. rules 没有提供下载. 或者兼容现有rule, 比如fortify,比如pmd. 等.  先Star先,

**Comment by wufeifei** [comment]
由于扫描规则属于核心资产，所以扫描规则的开放需要视情况而定。
对于其它系统的规则是兼容的，但需要做一些改动才能使用。
