### ISSUE TITLE
verify 字段是用来测试规则的么。

### ISSUE THREAD

**Issue by stayliv3** [wufeifei/cobra#288]
如果填错会有什么影响么

**Comment by wufeifei** [comment]
规则的测试用例，防止下次修改规则时对历史有影响。

具体写法可以看下
http://cobra-docs.readthedocs.io/en/latest/rule/

**Comment by stayliv3** [comment]
文档我都看过一遍了。  不是很理解防止下次修改规则时对历史有影响  的含义。修改规则之后，如果不修改规则的测试用例，匹配不上，这个规则就会不生效么。

**Comment by wufeifei** [comment]
就和代码的测试用例一个作用，防止你修改规则对之前扫描的漏洞会有影响，所以需要将各种情况写成测试用例。

后续计划是对规则用例自动测试，没有通过就不能上线。
