### ISSUE TITLE
unable to configure handler 'file':cannot not resolve 'cloghandler.ConcurrentRotatingFileHandler'

### ISSUE THREAD

**Issue by pythonone** [wufeifei/cobra#319]
### System and Python Environment
我已经用 npm安装了 cloc，是不是还需要在Ubuntu系统中再用apt-get install cloc才能避免这个错误？
unable to configure handler 'file':cannot not resolve 'cloghandler.ConcurrentRotatingFileHandler' ：no module named cloghandler

**Comment by wufeifei** [comment]
ConcurrentLogHandler==0.9.1未安装导致的
执行
```bash
cd /path/to/cobra/
pip install requirements.txt
```
