### ISSUE TITLE
Error 1698  - "Access denied for user 'root'@'localhost'"

### ISSUE THREAD

**Issue by Os3r3um** [wufeifei/cobra#320]
Hi there, 

Linux ubuntu 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.12+
Cobra v1.6.3 ( https://github.com/wufeifei/cobra )

### Description

Trying to perform the initial install function I'm getting "Access denied". Mysql server passwd was set to a NULL(void) value during initial install. 

python cobra.py install 
Start create database structure...
MySQL database error: (_mysql_exceptions.OperationalError) (1698, "Access denied for user 'root'@'localhost'")
FAQ: http://cobra-docs.readthedocs.io/en/latest/FAQ/

FAQ doesn't includes an clues about this probably simple situation. 

Any ideas? Do I miss something here?

Cheers.

**Comment by wufeifei** [comment]
MySQL config failed, see below:
http://cobra-docs.readthedocs.io/en/latest/configuration/
