### ISSUE TITLE
Export database structure file

### ISSUE THREAD

**Issue by wufeifei** [wufeifei/cobra#33]
Cobra database structure

**Comment by sechacking** [comment]
啥时候能上传数据库文件上来啊 ？：）

**Comment by wufeifei** [comment]
这周会将自动安装（包括表结构创建、测试扫描规则导入）完成：）

**Comment by wufeifei** [comment]
该问题已经完善，按照安装流程重新安装一遍即可。
https://github.com/wufeifei/cobra/wiki/Installation
