### ISSUE TITLE
admin/overview page gets TypeError

### ISSUE THREAD

**Issue by alioth310** [wufeifei/cobra#363]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`|CentOS 7|
|Python|`python -V`|2.7.5|
|Cobra|`python cobra.py`| 1.6.3（b87f5cf） |

### Description

If no record in database table `results`, admin/overview page will get an exception:

```
File "/home/workspace/cobra/app/controller/backend/index.py", line 240, in main
).group_by(CobraResults.status).first()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

### Steps to Reproduce

1. No record in table `results`
2. Login admin site, redirect to /admin/overview, then we get the error page (TypeError)
3. Review source code in `app/controller/backend/index.py`, I think the problem is `first()` method, when no record in result set, it will return None rather than [] or sth. else, so `first()[0]` will get TypeError.

I will submit a pull request to fix this bug.

**Comment by wufeifei** [comment]
Thanks a lot!
