### ISSUE TITLE
Dependency analysis and check dependencies vulnerability

### ISSUE THREAD

**Issue by Triater** [wufeifei/cobra#387]
三方包坐标 | 版本 | 使用频次 | 应用列表 | 隐患（可选）|
:----------- | :-----------: | :-----------: | :-----------: | :-----------: | 
com.alibaba:fastjson | 1.2.18 | 30 | itemcenter detailweb|
...         | ...        | ... | ... |... |

1. 统计项目所有pom.xml文件，分析每个依赖块
    
       <dependency>
          <groupId>com.alibaba</groupId>
          <artifactId>fastjson</artifactId>
          <version>1.2.28</version>
       </dependency>
       
2. 有两个麻烦的点
    
        1. 可能存在版本好用properties指定的方式
        <properties>
            <fastjson.version>1.2.28</fastjson.version>
        <properties>
        
        <dependencies>
           <dependency>
              <groupId>com.alibaba</groupId>
              <artifactId>fastjson</artifactId>
              <version>${fastjson.version}</version>
           </dependency>
        <dependencies>
        
        2. 可能版本号在父pom中
        
 3. 一个项目内某个坐标某个版本计数一次，不同版本各自计数，最好能记录下同项目中版本冲突的情况

**Comment by wufeifei** [comment]
`mvn dependency:list`
