### ISSUE TITLE
无法建立数据库表问题，python cobra.py install 无install此选项

### ISSUE THREAD

**Issue by z6101681** [wufeifei/cobra#40]
![image](https://cloud.githubusercontent.com/assets/15312660/17580461/661a0f84-5fd1-11e6-9759-8bb5ae1fea98.png)

**Comment by expdb2015** [comment]
1.[database]
mysql:mysql+mysqldb://user:pass@127.0.0.1:3306/cobra
2. mysql 创建数据库cobra

3. 执行 python cobra.py install

提示：在进行安装前，需要确认你的环境依赖是否有正确，如在python支持MySQLdb,
测试进入python命令行，输入 improt MySQLdb 如果无错误提示，执行第三步，初始化数据库，

**Comment by expdb2015** [comment]
你环境配置是否正常确，依赖的库在根目录requirements.txt里， sudo pip install -r requirements.txt 安装依赖，
在/cobra/app/__init__.py是数据初始化的代码，希望能帮到你！

**Comment by wufeifei** [comment]
更新最新代码，按照配置文件重新配置https://github.com/wufeifei/cobra/wiki/Config
