### ISSUE TITLE
[notice optimization] “Extensions distribution statistics” page

### ISSUE THREAD

**Issue by Xiaowang99** [wufeifei/cobra#407]
### Description

![image](https://cloud.githubusercontent.com/assets/4878878/25040601/0a1b253c-213d-11e7-99fd-7ff01c60d728.png)

### Steps to Reproduce

1. open  url "http://cobra.test.com/report/1?t=ext", the notice of the model "Extensions distribution statistics"  use "amount"  to count the number, I think "count" will be better.

**Comment by wufeifei** [comment]
fixed, thanks a lot!
