### ISSUE TITLE
 规则什么开放哦，提供一些简单也可以啦

### ISSUE THREAD

**Issue by 0xfcryowbk2ca65z** [wufeifei/cobra#411]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by wufeifei** [comment]
@0xfcryowbk2ca65z 
7月初左右新版本会出来

**Comment by danqing2008** [comment]
你好，什么时候公布这神器的规则啊。。等了好久了
