### ISSUE TITLE
这种简单规则查找的做法，误报会非常多吧？这种情况怎么处理？

### ISSUE THREAD

**Issue by huyuanmei** [wufeifei/cobra#412]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by wufeifei** [comment]
1. 就针对那些可以用规则100%匹配的漏洞，比如SSRF、输出型XSS、拼接型SQL注入、硬编码密码、不安全的三方依赖组件等等。
2. V2版本将在7月发布，接入AST，准确性将极大的提升。

**Comment by huyuanmei** [comment]
尝试了java代码扫描，规则是匹配的FileInputStream
fis = new java.io.FileInputStream("path");
这种代码也被报出了漏洞，貌似不能跟踪变量呀。
