### ISSUE TITLE
cobra使用问题

### ISSUE THREAD

**Issue by secsystem** [wufeifei/cobra#44]
你好，首先感谢关注Cobra，
1. 显示代码行数是异步通过cloc统计的，此处需要在报告中加个提示。扫不到漏洞是因为你的Cobra没有配置扫描规则，目前扫描规则还未同步整理上去。
2.
3. 直接弹出会被认为是广告，而被浏览器拦截。后面考虑扫完会显示报告的链接，点击链接跳转。（人工点击则不会被任务是广告）
4. 可以的，加入到Project表字段中
以上问题可以提到https://github.com/wufeifei/cobra/issues，让大家一起改进Cobra。
—

Best Regard

Feei - wufeifei@wufeifei.com

Site: http://wufeifei.com

Weibo: @吴止介 | Github: @wufeifei

On 2016年8月11日, at PM 11:43, secsystem

 你好 cobra作者，在微博看到这个项目感觉很棒，于是常识部署了下，但是在测试的时候遇到了如下问题，希望能在此得到解答！
1、在扫描完的时候没有显示整个项目行数，而且也扫不到漏洞我是拿的DVWA漏洞演示程序扫的！
2、使用私有git地址库，在config配置了用户名密码，但是在前端输入git地址的时候，服务端界面还是要求输入用户名密码
3、是否可以考虑扫描完直接转向或者弹出包括地址呢？而不是在url输入
4、项目对接人和项目pe是否可以动态获取
下面下我的运行截图，附件是log，不知是我部署的问题还是程序本身bug希望能够得到确认，谢谢！

**Comment by zhuangzhuangjtv** [comment]
您好，我在使用cobra连接gitlab项目时，提示Key verify failed，请问这个是什么问题

**Comment by BlBana** [comment]
这个在Cobra的配置文件 **config** 中需要配置一个key用于 **验证** API请求，在进行任务添加的时候需要附带上这个key
