### ISSUE TITLE
扫描不正常

### ISSUE THREAD

**Issue by semon9** [wufeifei/cobra#51]
安装正常，数据库连接创建也正常，但是开始扫描以后就一直转圈，就没有别的反应了。。
后台管理登录也没有反应，但是报告输出回显正常。
怎么解决？

**Comment by wufeifei** [comment]
因为扫描规则还未更新上去，所以报告是空的。
https://github.com/wufeifei/cobra/wiki/Rules

**Comment by semon9** [comment]
什么时候会给出规则更新？出来以后直接放入数据库就ok吗？

**Comment by wufeifei** [comment]
规则还在整理，到时候直接下载导入就好

**Comment by semon9** [comment]
好的，谢谢
