### ISSUE TITLE
关于安装的问题，谁来帮我一下

### ISSUE THREAD

**Issue by iamqiu** [wufeifei/cobra#53]
我一步步照着https://github.com/wufeifei/cobra/wiki/Installation做的，但是进行到pip install -r requirements.txt时候，总出现下面错误。我是centos7，x64.
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-2.7/MySQLdb/constants
    running build_ext
    building '_mysql' extension
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,2,5,'final',1) -D__version__=1.2.5 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
    _mysql.c:29:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of MySQL-python
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-hrCFx_/MySQL-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-TlCey9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hrCFx_/MySQL-python
[root@nginx cobra]# 
之后我想继续install，结果就出现
[root@nginx cobra]# python cobra.py install
Traceback (most recent call last):
  File "cobra.py", line 14, in <module>
    from app import web, manager
  File "/home/test/cobra/app/__init__.py", line 237, in <module>
    from app.controller import api
  File "/home/test/cobra/app/controller/api.py", line 20, in <module>
    from engine import scan
  File "/home/test/cobra/engine/scan.py", line 18, in <module>
    from utils import config, decompress
  File "/home/test/cobra/utils/decompress.py", line 18, in <module>
    import rarfile
ImportError: No module named rarfile
[root@nginx cobra]# 
估计是前面的依赖包没有装好，谁来指点一下怎么做呢

**Comment by wufeifei** [comment]
# Python
[sudo] yum install Python-devel

# MySQL
[sudo] yum install MySQL-python
[sudo] yum install mysql-devel

**Comment by wilsonleeee** [comment]
[root@localhost cobra]# python cobra.py install
Traceback (most recent call last):
  File "cobra.py", line 15, in <module>
    from app import web, manager
  File "/root/cobra/app/__init__.py", line 240, in <module>
    from app.controller import api
  File "/root/cobra/app/controller/api.py", line 20, in <module>
    from engine import scan
  File "/root/cobra/engine/scan.py", line 25, in <module>
    log.Log()
  File "/root/cobra/utils/log.py", line 26, in __init__
    logging.config.dictConfig({
AttributeError: 'module' object has no attribute 'dictConfig'

**Comment by wilsonleeee** [comment]
你好，请问这是什么问题

**Comment by wufeifei** [comment]
@wilsonleeee python版本问题，dictConfig是python2.7的特性
