### ISSUE TITLE
搭建在服务器上如何可以外联服务呢

### ISSUE THREAD

**Issue by v1cker** [wufeifei/cobra#55]
Hi wufeifei,
您好，想请教一下，搭建在服务器上，如何可以外联服务呢，只能本地访问吗，试着在config里修改ip和端口，无果，报错，无法请求地址 `socket.error: [Errno 99] Cannot assign requested address` ，是得配置nginx才可以吗
Thx

**Comment by wufeifei** [comment]
ip改成0.0.0.0即可外网访问
