### ISSUE TITLE
/api/report 的 task_id 如何获取

### ISSUE THREAD

**Issue by Zhiteng-Zhao** [wufeifei/cobra#556]
curl -H "Content-Type: application/json" -X POST -d '{"key":"your_secret_key","task_id": "your_task_id"}' http://127.0.0.1/api/report

请问以上API中，your_task_id哪得到，我试着填写/api/status返回数据中的sid，返回如下404
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```
请问如何解决，谢谢~

**Comment by wufeifei** [comment]
@Zhiteng-Zhao 
拿到status中的report就可以访问了，一般是这样的
```
127.0.0.1/?sid=a38186t714td
```

或者直接打开`127.0.0.1`来使用。

由于文档未更新，report这个API是不存在的。

**Comment by Zhiteng-Zhao** [comment]
那是不是 http://127.0.0.1/report/afbe69p7dxva/sfbe69plo5qs

> 扫描详情报告

也不存在，report后面那俩参数，我理解第一个是sid，第二个就不知道了

**Comment by wufeifei** [comment]
@40huo 帮忙解释下这个问题

**Comment by 40huo** [comment]
@Zhiteng-Zhao http://127.0.0.1/?sid=afbe69p7dxva&s_sid=sfbe69plo5qs，后面的是扫描的某个项目的 id

**Comment by Zhiteng-Zhao** [comment]
我猜也是这样的，所以我按照这种方式试过，但是报错，烦劳看看是不是有什么问题，谢谢~
```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

我的链接地址是这样的：
1. http://116.62.202.136:8888/?t=inf&sid=af61c5brpn1m&s_sid=sf61c5cb7bxg
正常显示
2. http://116.62.202.136:8888/report/af61c5brpn1m/sf61c5cb7bxg
异常，显示如上所述结果
