### ISSUE TITLE
python cobra.py --help 提示importError: cannot import name DependencyWarning

### ISSUE THREAD

**Issue by Gotric** [wufeifei/cobra#558]
python cobra.py --help 提示importError: cannot import name ,
pip install DependencyWarning提示No matching distribution found for DependencyWarning，
python版本2.7.13 pip版本9.0.1

**Comment by wufeifei** [comment]
@Gotric 错误信息贴全点

**Comment by Gotric** [comment]
#python cobra.py --help 
Traceback (most recent call last): File "cobra.py", line 7, 
in from cobra import main File "/opt/cobra/cobra/__init__.py", line 21, 
in from . import cli, api, config File "/opt/cobra/cobra/cli.py", line 16, 
in from .detection import Detection File "/opt/cobra/cobra/detection.py", line 20, 
in from pip.req import parse_requirements File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning ImportError: cannot import name DependencyWarning

#pip install DependencyWarning 
Collecting DependencyWarning 
Could not find a version that satisfies the requirement DependencyWarning (from versions: ) No matching distribution found for DependencyWarning

**Comment by wufeifei** [comment]
@Gotric 
猜测是你PIP问题，建议按照以下链接更新或重装pip。
https://github.com/infobyte/faraday/issues/164
