### ISSUE TITLE
yacc table file version is out of date

### ISSUE THREAD

**Issue by gourdbaby** [wufeifei/cobra#569]
### yacc table file version is out of date

在通过web服务进行检测的时候 出现上述提示，请问如何解决？

**Comment by wufeifei** [comment]
@gourdbaby 依赖的YACC存在问题，尝试重装下YACC试试

**Comment by BlBana** [comment]
ubuntu下可以通过
`sudo apt-get install flex bison `
更新yacc，解决版本过旧问题

**Comment by lucyxss** [comment]
macos: brew install flex
