### ISSUE TITLE
Can't get `param`, check built-in rule

### ISSUE THREAD

**Issue by mgiftdc** [wufeifei/cobra#579]
### Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
 and Python Environment
###python 2.7.9

### Description

运行时一直提示找不到参数，这是因为什么？
[13:33:12] [WARNING] [AST] Can't get `param`, check built-in rule
CLI和GUI下都是这样

**Comment by wufeifei** [comment]
有些语法解析不了导致的，后面完善解析引擎，避免因为语法错误之类的导致解析失败。

可忽略。

**Comment by mgiftdc** [comment]
好的，谢谢
