### ISSUE TITLE
增加查询正在扫描项目的接口

### ISSUE THREAD

**Issue by cxgreat2014** [wufeifei/cobra#598]
目前提交任务之后页面必须保持打开，一旦被关闭就无法再恢复打开。。而随便拿个项目一扫就是几十分钟，多人使用一台服务器测试速度更慢，一直保持这个页面打开也不现实，往往都是上传任务之后第二天再看结果的233，因此建议增加查询正在扫描的项目的接口，以及对过往扫描过的项目做个缓存记录，还有前端增加查看过去扫描过的项目。。233，感谢作者开发这个项目~

**Comment by wufeifei** [comment]
Web版本的扫描得一直打开，如果你手动调用扫描API就能拿到报告页，报告页在没有扫完的时候会显示正在扫描的项目。

报告页URL中会有一个sid，CLI模式扫的项目会有一个sid，记住这个sid，这样以后任何时候都可以通过这个sid访问对应的扫描报告。
