### ISSUE TITLE
规则如何下载导入呢

### ISSUE THREAD

**Issue by Gotric** [wufeifei/cobra#60]
请问规则应该如何下载导入，目前是否只有PHP的CURL SSRF规则，直接将规则复制进文档中在管理员页面add上传么

**Comment by DogeWatch** [comment]
自带的规则在哪呢 想找个模版对着写都找不到。。

**Comment by secsystem** [comment]
不知道把规则放到哪，也没见到规则模板，不知道怎么写规则才能被识别。。。。

**Comment by Gotric** [comment]
规则是在这里https://github.com/wufeifei/cobra/wiki/Rules

**Comment by wufeifei** [comment]
@secsystem @DogeWatch @Gotric 
目前开放了一个规则 https://github.com/wufeifei/cobra/wiki/rule_ssrf_curl
这个规则您可以写到rules表中

**Comment by wufeifei** [comment]
http://wufeifei.com/scan-engine/
完整的规则解释与例子可以看这篇。

**Comment by secsystem** [comment]
@wufeifei 谢谢解答，还有就是当前的版本不能在后台编辑完规则保存的时候显示保存成功，但是实际并没有写入，服务端还会报如下错误，用之前版本可以正常保存规则！
192.168.34.164 - - [25/Aug/2016 17:19:59] "POST /admin/graph_lines HTTP/1.1" 200 -
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/compiler.py:575: SAWarning: Can't resolve label reference 'id desc'; converting to text() (this warning may be suppressed after 10 occurrences)
  util.ellipses_string(element.element))
192.168.34.164 - - [25/Aug/2016 17:20:00] "GET /admin/rules/1 HTTP/1.1" 200 -

**Comment by wufeifei** [comment]
@secsystem 是的，因为改进了扫描规则引擎了，而后台的规则管理@LiGhT1EsS正在优化

**Comment by secsystem** [comment]
@wufeifei 额了解了，辛苦了，谢谢！
