### ISSUE TITLE
找出某个项目所有的扫描报告

### ISSUE THREAD

**Issue by DogeWatch** [wufeifei/cobra#61]
没有task删除选项么，还有能不能对所有项目做个列表并加个report链接呢，不然都不知道某个项目该对应的report/几

**Comment by wufeifei** [comment]
Task是不能删除的。
根据项目快速找出所有报告将作为Feature下个版本加上。

**Comment by wufeifei** [comment]
v1.6开始以及将项目id作为报告id了，此问题已解决。
