### ISSUE TITLE
[CVI-999xxx]999规则是否是默认扫描？？？

### ISSUE THREAD

**Issue by cyw3** [wufeifei/cobra#620]
![image](https://user-images.githubusercontent.com/11549103/33121378-7ef3d3ec-cfaf-11e7-84d2-17426d4ada35.png)

我在使用 **-r CVI-999002** 命令扫描时候，遇到以下问题：
![image](https://user-images.githubusercontent.com/11549103/33121467-d13f595a-cfaf-11e7-85ff-b22e15627000.png)

**Comment by wufeifei** [comment]
999系列规则是默认扫描的，无需指定
