### ISSUE TITLE
[结果输出]关于结果输出，不知道cobra考虑了数据量过大的情况吗？

### ISSUE THREAD

**Issue by cyw3** [wufeifei/cobra#622]
关于结果输出，不知道cobra考虑了数据量过大的情况吗？会不会导致内存溢出？
我看了下源码，发现只是使用文件直接写入的情况，不知道是不是这样。

**Comment by wufeifei** [comment]
扫描结果都是写入文件的，非恶意的正常扫描的数据量不会存在问题。
