### ISSUE TITLE
分析代码时报错

### ISSUE THREAD

**Issue by alwaystest18** [wufeifei/cobra#65]
分别在ubuntu和centos上装了一遍，都是这个报错，按wiki上安装时并未出现什么问题
`Traceback (most recent call last):
  File "/data/cobra/cobra.py", line 25, in <module>
    main()
  File "/data/cobra/cobra.py", line 21, in main
    manager.run()
  File "/usr/lib/python2.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/lib/python2.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/lib/python2.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/data/cobra/app/__init__.py", line 75, in run
    ['cloc', target], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by wufeifei** [comment]
目前还不支持SVN，你可以用Git或者上传压缩包的方式

**Comment by alwaystest18** [comment]
就是用的git报这个错，上传文件也是这样，获取文件没问题，是开始分析的时候报的这个错误

**Comment by wufeifei** [comment]
@alwaystest18 可以贴下/tmp/cobra/下的所有目录和你上传的文件名，我再看下

**Comment by alwaystest18** [comment]
目录比较多，我只帖部分吧，不过我觉得不是具体项目的问题，因为我测试了两个项目都是这种情况
上传文件名news.tar.gz,inf-data.tar.gz
`/tmp/cobra/
/tmp/cobra/uploads
/tmp/cobra/uploads/inf-data.tar
/tmp/cobra/uploads/inf-data.tar/inf-data
/tmp/cobra/uploads/inf-data.tar/inf-data/shell
/tmp/cobra/uploads/inf-data.tar/inf-data/mail_job
/tmp/cobra/uploads/inf-data.tar/inf-data/mail_job/caiwu
/tmp/cobra/uploads/inf-data.tar/inf-data/mail_job/app_stat
/tmp/cobra/uploads/inf-data.tar/inf-data/util
/tmp/cobra/uploads/inf-data.tar/inf-data/util/inf_data_util
...`

`/tmp/cobra/uploads/news.tar
/tmp/cobra/uploads/news.tar/data
/tmp/cobra/uploads/news.tar/data/staffnews
/tmp/cobra/uploads/news.tar/data/staffnews/api
/tmp/cobra/uploads/news.tar/data/staffnews/api/video_api
/tmp/cobra/uploads/news.tar/data/staffnews/caches
/tmp/cobra/uploads/news.tar/data/staffnews/caches/caches_search
/tmp/cobra/uploads/news.tar/data/staffnews/caches/caches_search/caches_data
...`
