### ISSUE TITLE
在规则的正则中添加常量

### ISSUE THREAD

**Issue by LiGhT1EsS** [wufeifei/cobra#69]
如果有如下定位规则：
``` regex
header\(.*?(\$[a-zA-Z_][a-zA-Z0-9_]+).*\)
```

其中\$[a-zA-Z_][a-zA-Z0-9_]+会出现多次，可以抽取为常量，例如{{PHPVar}}，方便规则编写，改写后的规则如下：
``` regex
header\(.*?({{PHPVar}}).*\)
```

对于该定位规则，如果修复规则为in_array($_GET["url"], $url_list);
需要在正则中再次使用匹配到的变量，所以可以使用常量进行解决，例如：
``` regex
in_array\({{MatchVar}},(.*)\)
```

**Comment by wufeifei** [comment]
```php
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt\s?\(.*,\s?CURLOPT_URL\s?,(.*)\)
```
所以取参应该是取出参数内所有字符(.*)，之后引擎会进行自动进行取参和判断。
